############################################################
# | ChestPreview by hexosse                              | #
############################################################


# *---------------- Plugin configuration --------------------*
plugin:
  # Enable metrics
  useMetrics : true
  # Enable updater
  useUpdater : true
  # Download update
  downloadUpdate: true


# *-------------- Messages configuration -----------------*
# You can use the default messages provided or translate as you whish.
messages: message_fr.yml


# *-------------- Chest location -----------------*
# List all the chest location.
chest.list: []


############################################################